import { RegistrationUserDto } from 'src/auth/dto/registration-user.dto';
import { Role } from 'src/common/constants';
import { CreatePlanetDto } from 'src/planet/dto/create-planet.dto';
import { UpdatePlanetDto } from 'src/planet/dto/update-planet.dto';
import { Planet } from 'src/planet/entities/planet.entity';

export const planetsStubArrayDefaultOpt = (): Planet[] => {
  const arrayPlanets: Planet[] = [
    {
      id: 1,
      created: new Date('2014-12-09T13:50:50.000Z'),
      edited: new Date('2014-12-20T20:58:18.000Z'),
      url: 'https://swapi.dev/api/planets/1/',
      name: 'Tatooine',
      rotation_period: '23',
      orbital_period: '304',
      diameter: '10465',
      climate: 'arid',
      gravity: '1 standard',
      terrain: 'desert',
      surface_water: '1',
      population: '200000',
      films: [],
      residents: [],
      images: [],
    },
    {
      id: 2,
      created: new Date('2014-12-10T11:35:48.000Z'),
      edited: new Date('2014-12-20T20:58:18.000Z'),
      url: 'https://swapi.dev/api/planets/2/',
      name: 'Alderaan',
      rotation_period: '24',
      orbital_period: '364',
      diameter: '12500',
      climate: 'temperate',
      gravity: '1 standard',
      terrain: 'grasslands, mountains',
      surface_water: '40',
      population: '2000000000',
      films: [],
      residents: [],
      images: [],
    },
    {
      id: 3,
      created: new Date('2014-12-10T11:37:19.000Z'),
      edited: new Date('2014-12-20T20:58:18.000Z'),
      url: 'https://swapi.dev/api/planets/3/',
      name: 'Yavin IV',
      rotation_period: '24',
      orbital_period: '4818',
      diameter: '10200',
      climate: 'temperate, tropical',
      gravity: '1 standard',
      terrain: 'jungle, rainforests',
      surface_water: '8',
      population: '1000',
      films: [],
      residents: [],
      images: [],
    },
    {
      id: 4,
      created: new Date('2014-12-10T11:39:14.000Z'),
      edited: new Date('2014-12-20T20:58:18.000Z'),
      url: 'https://swapi.dev/api/planets/4/',
      name: 'Hoth',
      rotation_period: '23',
      orbital_period: '549',
      diameter: '7200',
      climate: 'frozen',
      gravity: '1.1 standard',
      terrain: 'tundra, ice caves, mountain ranges',
      surface_water: '100',
      population: 'unknown',
      films: [],
      residents: [],
      images: [],
    },
    {
      id: 5,
      created: new Date('2014-12-10T11:42:23.000Z'),
      edited: new Date('2014-12-20T20:58:18.000Z'),
      url: 'https://swapi.dev/api/planets/5/',
      name: 'Dagobah',
      rotation_period: '23',
      orbital_period: '341',
      diameter: '8900',
      climate: 'murky',
      gravity: 'N/A',
      terrain: 'swamp, jungles',
      surface_water: '8',
      population: 'unknown',
      films: [],
      residents: [],
      images: [],
    },
    {
      id: 6,
      created: new Date('2014-12-10T11:43:55.000Z'),
      edited: new Date('2014-12-20T20:58:18.000Z'),
      url: 'https://swapi.dev/api/planets/6/',
      name: 'Bespin',
      rotation_period: '12',
      orbital_period: '5110',
      diameter: '118000',
      climate: 'temperate',
      gravity: '1.5 (surface), 1 standard (Cloud City)',
      terrain: 'gas giant',
      surface_water: '0',
      population: '6000000',
      films: [],
      residents: [],
      images: [],
    },
    {
      id: 7,
      created: new Date('2014-12-10T11:50:29.000Z'),
      edited: new Date('2014-12-20T20:58:18.000Z'),
      url: 'https://swapi.dev/api/planets/7/',
      name: 'Endor',
      rotation_period: '18',
      orbital_period: '402',
      diameter: '4900',
      climate: 'temperate',
      gravity: '0.85 standard',
      terrain: 'forests, mountains, lakes',
      surface_water: '8',
      population: '30000000',
      films: [],
      residents: [],
      images: [],
    },
    {
      id: 8,
      created: new Date('2014-12-10T11:52:31.000Z'),
      edited: new Date('2014-12-20T20:58:18.000Z'),
      url: 'https://swapi.dev/api/planets/8/',
      name: 'Naboo',
      rotation_period: '26',
      orbital_period: '312',
      diameter: '12120',
      climate: 'temperate',
      gravity: '1 standard',
      terrain: 'grassy hills, swamps, forests, mountains',
      surface_water: '12',
      population: '4500000000',
      films: [],
      residents: [],
      images: [],
    },
    {
      id: 9,
      created: new Date('2014-12-10T11:54:14.000Z'),
      edited: new Date('2014-12-20T20:58:18.000Z'),
      url: 'https://swapi.dev/api/planets/9/',
      name: 'Coruscant',
      rotation_period: '24',
      orbital_period: '368',
      diameter: '12240',
      climate: 'temperate',
      gravity: '1 standard',
      terrain: 'cityscape, mountains',
      surface_water: 'unknown',
      population: '1000000000000',
      films: [],
      residents: [],
      images: [],
    },
    {
      id: 10,
      created: new Date('2014-12-10T12:45:07.000Z'),
      edited: new Date('2014-12-20T20:58:18.000Z'),
      url: 'https://swapi.dev/api/planets/10/',
      name: 'Kamino',
      rotation_period: '27',
      orbital_period: '463',
      diameter: '19720',
      climate: 'temperate',
      gravity: '1 standard',
      terrain: 'ocean',
      surface_water: '100',
      population: '1000000000',
      films: [],
      residents: [],
      images: [],
    },
  ];
  return arrayPlanets;
};
export const planetsStubArrayPage2Limit2 = (): Planet[] => {
  const planetArray: Planet[] = [
    {
      id: 3,
      created: new Date('2014-12-10T11:37:19.000Z'),
      edited: new Date('2014-12-20T20:58:18.000Z'),
      url: 'https://swapi.dev/api/planets/3/',
      name: 'Yavin IV',
      rotation_period: '24',
      orbital_period: '4818',
      diameter: '10200',
      climate: 'temperate, tropical',
      gravity: '1 standard',
      terrain: 'jungle, rainforests',
      surface_water: '8',
      population: '1000',
      films: [],
      residents: [],
      images: [],
    },
    {
      id: 4,
      created: new Date('2014-12-10T11:39:14.000Z'),
      edited: new Date('2014-12-20T20:58:18.000Z'),
      url: 'https://swapi.dev/api/planets/4/',
      name: 'Hoth',
      rotation_period: '23',
      orbital_period: '549',
      diameter: '7200',
      climate: 'frozen',
      gravity: '1.1 standard',
      terrain: 'tundra, ice caves, mountain ranges',
      surface_water: '100',
      population: 'unknown',
      films: [],
      residents: [],
      images: [],
    },
  ];
  return planetArray;
};

export const errorNotFoundStub = () => {
  return {
    message: 'Planet not found in database.',
    statusCode: 404,
  };
};

export const userStubRegDto = (): RegistrationUserDto => {
  return {
    username: 'adminTest',
    email: 'adminTest@gmail.com',
    password: 'adminTest',
    passwordRepeated: 'adminTest',
    role: Role.Admin,
  };
};

export const planetStubCreateDto = (): CreatePlanetDto => {
  return {
    name: '',
    rotation_period: '0',
    orbital_period: '0',
    diameter: '0',
    climate: 'planet',
    gravity: 'planet',
    terrain: 'planet',
    surface_water: 'planet',
    population: 'planet',
    residents: [],
    films: [],
  };
};
