version: '3.1'
networks:
  swapi_network:
    driver: bridge

services:
  mysqldb:
    image: mysql
    container_name: mysqldb
    ports:
      - ${DATABASE_PORT}:3306
    environment:
      MYSQL_DATABASE: ${DATABASE}
      MYSQL_USER: ${DATABASE_USER}
      MYSQL_PASSWORD: ${DATABASE_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${ROOT_PASSWORD}
    volumes:
      - myapp:/home/app
    restart: always
    env_file:
      - .env
    networks:
      - swapi_network

  phpmyadmin:
    image: phpmyadmin
    container_name: phpmyadmin
    restart: always
    ports:
      - 8082:80
    environment:
      - PMA_ARBITRARY=1
    networks:
      - swapi_network
    links:
      - mysqldb
      - testdb

  testdb:
    image: mysql
    container_name: testdb
    ports:
      - ${DATABASE_TEST_PORT}:3306
    environment:
      MYSQL_DATABASE: ${TEST_DATABASE}
      MYSQL_USER: ${TEST_DATABASE_USER}
      MYSQL_PASSWORD: ${TEST_DATABASE_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${ROOT_PASSWORD}
    volumes:
      - myapp:/home/app/test/1
    restart: always
    env_file:
      - .env
    networks:
      - swapi_network
volumes:
  myapp:
