version: '3.1'
networks:
  swapi_network:
    driver: bridge

services:
  mysqldb:
    image: mysql
    container_name: mysql-container
    ports:
      - 3307:${DATABASE_PORT}
    environment:
      MYSQL_DATABASE: ${DATABASE}
      MYSQL_DATABASE_USER: ${DATABASE_USER}
      MYSQL_DATABASE_PASSWORD: ${DATABASE_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${ROOT_PASSWORD}
    volumes:
      - myapp:/home/app
    restart: always
    env_file:
      - .env
    networks:
      - swapi_network

  phpmyadmin:
    image: phpmyadmin
    container_name: phpmyadmin
    restart: always
    ports:
      - 8082:80
    environment:
      - PMA_ARBITRARY=1
    networks:
      - swapi_network
    links:
      - mysqldb
      - testdb

  testdb:
    image: mysql
    container_name: test-container
    ports:
      - 3308:${DATABASE_PORT}
    environment:
      MYSQL_DATABASE: ${TEST_DATABASE}
      MYSQL_DATABASE_USER: ${TEST_DATABASE_USER}
      MYSQL_DATABASE_PASSWORD: ${TEST_DATABASE_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${ROOT_PASSWORD}
    volumes:
      - myapp:/home/app/test
    restart: always
    env_file:
      - .env
    networks:
      - swapi_network
volumes:
  myapp:
