version: '3.1'
networks:
  starwarsnetwork:
    driver: bridge

services:
  mysql:
    image: mysql
    container_name: mysql
    ports:
      - 3307:${DATABASE_PORT}
    environment:
      MYSQL_DATABASE: ${DATABASE}
      MYSQL_DATABASE_USER: ${DATABASE_USER}
      MYSQL_DATABASE_PASSWORD: ${DATABASE_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${ROOT_PASSWORD}
    volumes:
      - myapp:/home/app
    restart: always
    env_file:
      - .env.image
    networks:
      - starwarsnetwork

  phpmyadmin:
    image: phpmyadmin
    container_name: phpmyadmin
    restart: always
    ports:
      - 8081:80
    environment:
      - PMA_ARBITRARY=1
    networks:
      - starwarsnetwork

  test:
    image: mysql
    container_name: test
    ports:
      - 3308:${DATABASE_PORT}
    environment:
      MYSQL_DATABASE: ${TEST_DATABASE}
      MYSQL_DATABASE_USER: ${TEST_DATABASE_USER}
      MYSQL_DATABASE_PASSWORD: ${TEST_DATABASE_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${ROOT_PASSWORD}
    volumes:
      - myapp:/home/app/test
    restart: always
      env_file:
      - .env.image
    networks:
      - starwarsnetwork
volumes:
  myapp:
