version: '3.1'
networks:
  starwars_network:
    driver: bridge

services:
  mysql-db:
    image: mysql
    container_name: mysql-db
    ports:
      - 3307:${DATABASE_PORT}
    environment:
      MYSQL_DATABASE: ${DATABASE}
      MYSQL_DATABASE_USER: ${DATABASE_USER}
      MYSQL_DATABASE_PASSWORD: ${DATABASE_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${ROOT_PASSWORD}
    volumes:
      - myapp:/home/app
    restart: always
    networks:
      - starwars_network

  starwars:
    image: irynakos/starwars
    container_name: starwars
    ports:
      - ${APP_PORT}:${APP_PORT}
    networks:
      - starwars_network
    env_file:
      - .env
    depends_on:
      - 'mysql-db'
      - 'test-db'
    restart: always

  test-db:
    image: mysql
    container_name: test-db
    ports:
      - 3308:${DATABASE_PORT}
    environment:
      MYSQL_DATABASE: ${TEST_DATABASE}
      MYSQL_DATABASE_USER: ${TEST_DATABASE_USER}
      MYSQL_DATABASE_PASSWORD: ${TEST_DATABASE_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${ROOT_PASSWORD}
    volumes:
      - myapp:/home/app/test
    restart: always
    networks:
      - starwars_network
volumes:
  myapp:
