version: '3.1'
networks:
  starwarsnetwork:
    driver: bridge

services:
  db_mysql:
    image: mysql
    container_name: db_mysql
    ports:
      - ${MY_DATABASE_PORT}:${DATABASE_PORT}
    env_file:
      - .env
    environment:
      MYSQL_DATABASE: ${DATABASE}
      MYSQL_USER: ${DATABASE_USER}
      MYSQL_PASSWORD: ${DATABASE_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    volumes:
      - myapp:/home/app/db
    restart: always
    networks:
      - starwarsnetwork

  starwars:
    image: irynakos/starwars:latest
    container_name: starwars
    ports:
      - ${APP_PORT}:${APP_PORT}
    networks:
      - starwarsnetwork
    env_file:
      - .env
    links:
      - db_mysql
      - phpmyadmin
    environment:
      MYSQL_DATABASE_HOST: ${DATABASE_HOST}
      MYSQL_USER: ${DATABASE_USER}
      MYSQL_PASSWORD: ${DATABASE_PASSWORD}
    restart: always

  phpmyadmin:
    image: phpmyadmin
    container_name: phpmyadmin
    restart: always
    ports:
      - 8081:80
    environment:
      - PMA_ARBITRARY=1
    networks:
      - starwarsnetwork
    links:
      - db_mysql

volumes:
  myapp:
