version: '3.1'
networks:
  starwars_network:
    driver: bridge

services:
  mysql-db:
    image: mysql
    container_name: mysql-db
    ports:
      - 3309:3306
    env_file:
      - .env.image
    environment:
      MYSQL_DATABASE: ${DATABASE}
      MYSQL_USER: ${DATABASE_USER}
      MYSQL_PASSWORD: ${DATABASE_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${ROOT_PASSWORD}
    volumes:
      - myapp:/home/app
    restart: always
    networks:
      - starwars_network

  starwars:
    image: irynakos/starwars
    container_name: starwars
    ports:
      - 3001:3001
    networks:
      - starwars_network
    env_file:
      - .env.image
    links:
      - mysql-db
      - phpmyadmin
    restart: always

  phpmyadmin:
    image: phpmyadmin
    container_name: phpmyadmin
    restart: always
    ports:
      - 8081:80
    environment:
      - PMA_ARBITRARY=1
    networks:
      - starwars_network
    links:
      - mysql-db
volumes:
  myapp:
